name: Verify Commit signature
on:
  push:
  pull_request:

permissions:
  contents: read
jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify commit
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: chainguard-dev/actions/setup-gitsign@main
      - shell: bash
        run: |
          git verify-commit HEAD