name: Enforce - Commit Signing
on:
  push:
  pull_request:

permissions:
  contents: read
jobs:
  verify-commit:
    runs-on: ubuntu-latest
    name: Verify commit
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: chainguard-dev/actions/setup-gitsign@main
      - shell: bash
        run: |
          git verify-commit HEAD
  verify-signature:
    runs-on: ubuntu-latest
    name: Verify git signature against authority
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: chainguard-dev/actions/setup-gitsign@main
      - shell: bash
        run: gitsign verify --certificate-identity=${{ github.event.pusher.email }} --certificate-oidc-issuer=https://github.com/login/oauth HEAD